### ISSUE TITLE
no unity project folder?

### ISSUE THREAD

**Issue by AtlasTitanium** [rolopogo/CustomPlatforms#4]
in the README you say that to make a custom platform i need to "Open the Unity project in the "Unity Project" folder".  but there's no unity project folder? or am i looking in the wrong place?

**Comment by SephTheTraitor** [comment]
Heya! Dunno if you're still trying to find it, but it's under releases - https://github.com/rolopogo/CustomPlatforms/releases

I checked this out myself yesterday. I've used Unity before, but it seems pretty confusing to follow that guide. I got the latest version of Unity though (2018.2). The project was last saved with 2018.1. I get alerts about Unity updates or opening a project with a newer version of Unity, but I chose to use the latest Unity instead. I hope this hasn't broken anything!

I actually couldn't figure out how to begin creating my own platform or even export the example one to a .plat, so please let me know if you figure that out :D

**Comment by Assistant** [comment]
@SephTheTraitor Unfortunately that does break the project, that's why you couldn't export the platform. You'll want to use 2018.1.6f1. You can find a guide on how to make platforms [here](https://bs.assistant.moe/Platforms/).

**Comment by rolopogo** [comment]
I've updated the readme, and included a link to Emma's platform creation tutorial.
Hopefully things are clearer now.
